-- Prisma creates tables through SQL rather than the Supabase table editor, so
-- RLS is not enabled automatically. The mobile app talks only to the Express
-- API; no anon/authenticated Data API policies are intentionally granted here.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Budget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BudgetItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BudgetItemSplit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmergencyContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SearchHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedPlace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Review" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Translation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Itinerary" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Follow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Story" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Like" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ViewedPlace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankTransferOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PremiumGrant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SharedBudget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SharedItinerary" ENABLE ROW LEVEL SECURITY;
